version: '3.8'

services:
  web:
    build: .
    container_name: dr-cdss-app
    ports:
      - "5000:5000"
    volumes:
      - ./uploads:/app/uploads
      - ./logs:/app/logs
      - ./models:/app/models
    restart: always
    environment:
      - FLASK_ENV=production
      - SECRET_KEY=dr-cdss-secret-2024-xk9q
